version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_mgmt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed_db:/docker-entrypoint-initdb.d
    command: >
      bash -c "
      docker-entrypoint.sh postgres &&
      psql -U postgres -d school_mgmt -f /docker-entrypoint-initdb.d/tables.sql &&
      psql -U postgres -d school_mgmt -f /docker-entrypoint-initdb.d/seed-db.sql
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
